/* 
This file was generated by a tool. Any changes made to this file will be lost if the code is regenerated.
xml generated from http://xmltocsharp.azurewebsites.net
*/

using System.Xml.Serialization;
namespace VontobelTest.src.models
{
	[XmlRoot(ElementName="AdminData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class AdminData {
		[XmlElement(ElementName="SubmitterInternalReference", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? SubmitterInternalReference { get; set; }
		[XmlElement(ElementName="DefinitiveTermsFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DefinitiveTermsFlag { get; set; }
		[XmlElement(ElementName="SimulationFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? SimulationFlag { get; set; }
		[XmlElement(ElementName="EffectiveFromDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? EffectiveFromDate { get; set; }
		[XmlElement(ElementName="CorrelationId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CorrelationId { get; set; }
		[XmlElement(ElementName="Receiver", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? Receiver { get; set; }
		[XmlElement(ElementName="IssuerId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IssuerId { get; set; }
		[XmlElement(ElementName="DistributorId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DistributorId { get; set; }
		[XmlElement(ElementName="TrackingId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? TrackingId { get; set; }
		[XmlElement(ElementName="DistributorReferenceId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DistributorReferenceId { get; set; }
		[XmlElement(ElementName="MessageStatus", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? MessageStatus { get; set; }
		[XmlElement(ElementName="Custodian", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? Custodian { get; set; }
	}

	[XmlRoot(ElementName="Event", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Event {
		[XmlElement(ElementName="EventType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? EventType { get; set; }
		[XmlElement(ElementName="UpdateComment", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UpdateComment { get; set; }
	}

	[XmlRoot(ElementName="Events", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Events {
		[XmlElement(ElementName="Event", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public Event? Event { get; set; }
	}

	[XmlRoot(ElementName="Contact", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Contact {
		[XmlElement(ElementName="ContactType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ContactType { get; set; }
		[XmlElement(ElementName="ContactName", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ContactName { get; set; }
		[XmlElement(ElementName="TelephoneNo", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? TelephoneNo { get; set; }
		[XmlElement(ElementName="FaxNo", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FaxNo { get; set; }
		[XmlElement(ElementName="EmailAddress", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? EmailAddress { get; set; }
	}

	[XmlRoot(ElementName="Contacts", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Contacts {
		[XmlElement(ElementName="Contact", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public List<Contact>? Contact { get; set; }
	}

	[XmlRoot(ElementName="LossBearingCapacity", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class LossBearingCapacity {
		[XmlElement(ElementName="NoCapitalLossType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? NoCapitalLossType { get; set; }
		[XmlElement(ElementName="PartialCapitalLossType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PartialCapitalLossType { get; set; }
		[XmlElement(ElementName="LossUpToCapitalPercentage", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LossUpToCapitalPercentage { get; set; }
		[XmlElement(ElementName="TotalCapitalLossType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? TotalCapitalLossType { get; set; }
		[XmlElement(ElementName="LossGreaterCapitalType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LossGreaterCapitalType { get; set; }
	}

	[XmlRoot(ElementName="KnowledgeExperience", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class KnowledgeExperience {
		[XmlElement(ElementName="BasicKnowledgeType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BasicKnowledgeType { get; set; }
		[XmlElement(ElementName="InformedKnowledgeType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InformedKnowledgeType { get; set; }
		[XmlElement(ElementName="AdvancedKnowledgeType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? AdvancedKnowledgeType { get; set; }
		[XmlElement(ElementName="ExpertKnowledge", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ExpertKnowledge { get; set; }
	}

	[XmlRoot(ElementName="CustomerCategory", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class CustomerCategory {
		[XmlElement(ElementName="PrivateCustomerType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PrivateCustomerType { get; set; }
		[XmlElement(ElementName="ProfessionalCustomerType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ProfessionalCustomerType { get; set; }
		[XmlElement(ElementName="QualifiedCounterpartyType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? QualifiedCounterpartyType { get; set; }
	}

	[XmlRoot(ElementName="InvestmentTargets", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class InvestmentTargets {
		[XmlElement(ElementName="SpecificRetirementSchemeType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? SpecificRetirementSchemeType { get; set; }
		[XmlElement(ElementName="PreservationType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PreservationType { get; set; }
		[XmlElement(ElementName="InvestmentIncomeType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InvestmentIncomeType { get; set; }
		[XmlElement(ElementName="GrowthType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? GrowthType { get; set; }
		[XmlElement(ElementName="FinancingType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FinancingType { get; set; }
		[XmlElement(ElementName="HedgingType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? HedgingType { get; set; }
		[XmlElement(ElementName="LeverageType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LeverageType { get; set; }
	}

	[XmlRoot(ElementName="InvestmentHorizon", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class InvestmentHorizon {
		[XmlElement(ElementName="VeryShortTermType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? VeryShortTermType { get; set; }
		[XmlElement(ElementName="ShortTermType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ShortTermType { get; set; }
		[XmlElement(ElementName="MediumTermType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? MediumTermType { get; set; }
		[XmlElement(ElementName="LongTermType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LongTermType { get; set; }
		[XmlElement(ElementName="HeldToMaturityType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? HeldToMaturityType { get; set; }
		[XmlElement(ElementName="RecommendedHoldingPeriod", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RecommendedHoldingPeriod { get; set; }
		[XmlElement(ElementName="MayBeTerminatedEarlyType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? MayBeTerminatedEarlyType { get; set; }
	}

	[XmlRoot(ElementName="DistributionStrategy", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class DistributionStrategy {
		[XmlElement(ElementName="ExecutionOnlyType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ExecutionOnlyType { get; set; }
		[XmlElement(ElementName="TransactionWithoutConsultingType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? TransactionWithoutConsultingType { get; set; }
		[XmlElement(ElementName="InvestmentConsultingType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InvestmentConsultingType { get; set; }
		[XmlElement(ElementName="PortfolioManagementType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PortfolioManagementType { get; set; }
	}

	[XmlRoot(ElementName="SpecialRequirements", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class SpecialRequirements {
		[XmlElement(ElementName="GreenInvestmentType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? GreenInvestmentType { get; set; }
		[XmlElement(ElementName="EthicalInvestmentType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? EthicalInvestmentType { get; set; }
		[XmlElement(ElementName="IslamicBankingType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IslamicBankingType { get; set; }
	}

	[XmlRoot(ElementName="MiFIDPRIIPData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class MiFIDPRIIPData {
		[XmlElement(ElementName="LeveragedInstrumentFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LeveragedInstrumentFlag { get; set; }
		[XmlElement(ElementName="InstrumentComplexityType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InstrumentComplexityType { get; set; }
		[XmlElement(ElementName="LossBearingCapacity", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public LossBearingCapacity? LossBearingCapacity { get; set; }
		[XmlElement(ElementName="KnowledgeExperience", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public KnowledgeExperience? KnowledgeExperience { get; set; }
		[XmlElement(ElementName="RiskIndicatorType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RiskIndicatorType { get; set; }
		[XmlElement(ElementName="RiskYieldProfileType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RiskYieldProfileType { get; set; }
		[XmlElement(ElementName="CustomerCategory", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public CustomerCategory? CustomerCategory { get; set; }
		[XmlElement(ElementName="InvestmentTargets", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public InvestmentTargets? InvestmentTargets { get; set; }
		[XmlElement(ElementName="InvestmentHorizon", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public InvestmentHorizon? InvestmentHorizon { get; set; }
		[XmlElement(ElementName="DistributionStrategy", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public DistributionStrategy? DistributionStrategy { get; set; }
		[XmlElement(ElementName="SpecialRequirements", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public SpecialRequirements? SpecialRequirements { get; set; }
	}

	[XmlRoot(ElementName="FIDLEGData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class FIDLEGData {
		[XmlElement(ElementName="InstrumentInScopeFIDLEG", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InstrumentInScopeFIDLEG { get; set; }
		[XmlElement(ElementName="FIDLEGDocumentationSubmissionType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FIDLEGDocumentationSubmissionType { get; set; }
	}

	[XmlRoot(ElementName="RegulatoryData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class RegulatoryData {
		[XmlElement(ElementName="MiFIDPRIIPData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public MiFIDPRIIPData? MiFIDPRIIPData { get; set; }
		[XmlElement(ElementName="FIDLEGData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public FIDLEGData? FIDLEGData { get; set; }
	}

	[XmlRoot(ElementName="InstrumentClassification", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class InstrumentClassification {
		[XmlElement(ElementName="ClassificationSchemeType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ClassificationSchemeType { get; set; }
		[XmlElement(ElementName="ClassificationValue", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ClassificationValue { get; set; }
	}

	[XmlRoot(ElementName="InstrumentClassifications", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class InstrumentClassifications {
		[XmlElement(ElementName="InstrumentClassification", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public List<InstrumentClassification>? InstrumentClassification { get; set; }
	}

	[XmlRoot(ElementName="IncomeData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class IncomeData {
		[XmlElement(ElementName="InterestComponentFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InterestComponentFlag { get; set; }
		[XmlElement(ElementName="IncomePeriodicType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IncomePeriodicType { get; set; }
		[XmlElement(ElementName="IncomeInterval", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IncomeInterval { get; set; }
		[XmlElement(ElementName="IncomeIntervalType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IncomeIntervalType { get; set; }
		[XmlElement(ElementName="InterestPeriodAdjustmentFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InterestPeriodAdjustmentFlag { get; set; }
		[XmlElement(ElementName="AnnualIncomeRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? AnnualIncomeRate { get; set; }
		[XmlElement(ElementName="FirstPaymentDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FirstPaymentDate { get; set; }
		[XmlElement(ElementName="InterestFromDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InterestFromDate { get; set; }
		[XmlElement(ElementName="IncomeValuationBusinessDays", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IncomeValuationBusinessDays { get; set; }
		[XmlElement(ElementName="FirstCouponStub", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FirstCouponStub { get; set; }
	}

	[XmlRoot(ElementName="CHTaxData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class CHTaxData {
		[XmlElement(ElementName="AnnualInterestFractionRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? AnnualInterestFractionRate { get; set; }
		[XmlElement(ElementName="InterestFractionRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InterestFractionRate { get; set; }
		[XmlElement(ElementName="AnnualPremiumFractionRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? AnnualPremiumFractionRate { get; set; }
		[XmlElement(ElementName="PremiumFractionRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PremiumFractionRate { get; set; }
		[XmlElement(ElementName="CHIUPType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CHIUPType { get; set; }
		[XmlElement(ElementName="CHIssueStampTaxFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CHIssueStampTaxFlag { get; set; }
		[XmlElement(ElementName="StampTaxFeedbackFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StampTaxFeedbackFlag { get; set; }
		[XmlElement(ElementName="CHTurnoverStampTaxFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CHTurnoverStampTaxFlag { get; set; }
		[XmlElement(ElementName="CHTaxType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CHTaxType { get; set; }
		[XmlElement(ElementName="CHWithholdingTaxRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CHWithholdingTaxRate { get; set; }
	}

	[XmlRoot(ElementName="EUTaxData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class EUTaxData {
		[XmlElement(ElementName="EUTaxType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? EUTaxType { get; set; }
		[XmlElement(ElementName="EUTaxApplicabilityType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? EUTaxApplicabilityType { get; set; }
	}

	[XmlRoot(ElementName="IRS871m", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class IRS871m {
		[XmlElement(ElementName="ContractComplexityType871m", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ContractComplexityType871m { get; set; }
		[XmlElement(ElementName="IssuersInstrumentInScope871m", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IssuersInstrumentInScope871m { get; set; }
		[XmlElement(ElementName="TaxPaidByIssuerFlag871m", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? TaxPaidByIssuerFlag871m { get; set; }
	}

	[XmlRoot(ElementName="USTaxData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class USTaxData {
		[XmlElement(ElementName="USTaxType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? USTaxType { get; set; }
		[XmlElement(ElementName="IRS871m", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public IRS871m? IRS871m { get; set; }
	}

	[XmlRoot(ElementName="UKTaxData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class UKTaxData {
		[XmlElement(ElementName="UKDDS", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UKDDS { get; set; }
		[XmlElement(ElementName="UKCapitalGainsTax", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UKCapitalGainsTax { get; set; }
	}

	[XmlRoot(ElementName="ATTaxData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class ATTaxData {
		[XmlElement(ElementName="ATKESt", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ATKESt { get; set; }
		[XmlElement(ElementName="ATInvestFund", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ATInvestFund { get; set; }
	}

	[XmlRoot(ElementName="ITTaxData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class ITTaxData {
		[XmlElement(ElementName="ITTransactionTax", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ITTransactionTax { get; set; }
	}

	[XmlRoot(ElementName="Fee", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Fee {
		[XmlElement(ElementName="FeeType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FeeType { get; set; }
		[XmlElement(ElementName="FeeBaseType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FeeBaseType { get; set; }
		[XmlElement(ElementName="FeeRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FeeRate { get; set; }
		[XmlElement(ElementName="AnnualFeeRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? AnnualFeeRate { get; set; }
		[XmlElement(ElementName="FeeValue", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FeeValue { get; set; }
		[XmlElement(ElementName="FeePaymentCurrencyCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FeePaymentCurrencyCode { get; set; }
		[XmlElement(ElementName="FeePaymentPeriodicType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FeePaymentPeriodicType { get; set; }
		[XmlElement(ElementName="FeePaymentInterval", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FeePaymentInterval { get; set; }
		[XmlElement(ElementName="FeePaymentIntervalType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FeePaymentIntervalType { get; set; }
	}

	[XmlRoot(ElementName="Fees", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Fees {
		[XmlElement(ElementName="Fee", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public List<Fee>? Fee { get; set; }
	}

	[XmlRoot(ElementName="InstrumentId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class InstrumentId {
		[XmlElement(ElementName="IdSchemeCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IdSchemeCode { get; set; }
		[XmlElement(ElementName="IdValue", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IdValue { get; set; }
	}

	[XmlRoot(ElementName="ReutersInstrumentId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class ReutersInstrumentId {
		[XmlElement(ElementName="RICode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RICode { get; set; }
	}

	[XmlRoot(ElementName="InstrumentIds", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class InstrumentIds {
		[XmlElement(ElementName="InstrumentId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public List<InstrumentId>? InstrumentId { get; set; }
		[XmlElement(ElementName="ReutersInstrumentId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public ReutersInstrumentId? ReutersInstrumentId { get; set; }
		[XmlElement(ElementName="BloombergInstrumentId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public BloombergInstrumentId? BloombergInstrumentId { get; set; }
	}

	[XmlRoot(ElementName="BloombergInstrumentId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class BloombergInstrumentId {
		[XmlElement(ElementName="BBTickerSymbol", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BBTickerSymbol { get; set; }
		[XmlElement(ElementName="BBExchangeCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BBExchangeCode { get; set; }
		[XmlElement(ElementName="BBMarketSectorCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BBMarketSectorCode { get; set; }
	}

	[XmlRoot(ElementName="Underlying", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Underlying {
		[XmlElement(ElementName="UnderlyingKey", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingKey { get; set; }
		[XmlElement(ElementName="NameShort", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? NameShort { get; set; }
		[XmlElement(ElementName="NameLong", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? NameLong { get; set; }
		[XmlElement(ElementName="PrincipalFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PrincipalFlag { get; set; }
		[XmlElement(ElementName="IncomeFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IncomeFlag { get; set; }
		[XmlElement(ElementName="PaymentLegFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentLegFlag { get; set; }
		[XmlElement(ElementName="UnderlyingRoleType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingRoleType { get; set; }
		[XmlElement(ElementName="UnderlyingQuotedPriceType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingQuotedPriceType { get; set; }
		[XmlElement(ElementName="FXPriceInverseFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FXPriceInverseFlag { get; set; }
		[XmlElement(ElementName="FXUnderlyingCurrencyCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FXUnderlyingCurrencyCode { get; set; }
		[XmlElement(ElementName="QuotedCurrencyCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? QuotedCurrencyCode { get; set; }
		[XmlElement(ElementName="UnderlyingAssetType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingAssetType { get; set; }
		[XmlElement(ElementName="UnderlyingType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingType { get; set; }
		[XmlElement(ElementName="UnderlyingSubType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingSubType { get; set; }
		[XmlElement(ElementName="RolloverFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RolloverFlag { get; set; }
		[XmlElement(ElementName="UnderlyingExchangeCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingExchangeCode { get; set; }
		[XmlElement(ElementName="MonetiserAmount", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? MonetiserAmount { get; set; }
		[XmlElement(ElementName="MonetiserCurrencyCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? MonetiserCurrencyCode { get; set; }
		[XmlElement(ElementName="InitialReferencePrice", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InitialReferencePrice { get; set; }
		[XmlElement(ElementName="AdjustedReferencePrice", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? AdjustedReferencePrice { get; set; }
		[XmlElement(ElementName="LatestReferencePrice", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LatestReferencePrice { get; set; }
		[XmlElement(ElementName="FinalReferencePrice", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FinalReferencePrice { get; set; }
		[XmlElement(ElementName="UnderlyingCoverRatio", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingCoverRatio { get; set; }
		[XmlElement(ElementName="UnderlyingReverseCoverRatio", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingReverseCoverRatio { get; set; }
		[XmlElement(ElementName="CurrentAmount", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CurrentAmount { get; set; }
		[XmlElement(ElementName="CurrentWeight", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CurrentWeight { get; set; }
		[XmlElement(ElementName="CurrencyPairSymbol", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CurrencyPairSymbol { get; set; }
		[XmlElement(ElementName="CurrencyPairSpotRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CurrencyPairSpotRate { get; set; }
		[XmlElement(ElementName="CurrencyPairFeedType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CurrencyPairFeedType { get; set; }
		[XmlElement(ElementName="CurrencyPairSourcePage", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CurrencyPairSourcePage { get; set; }
		[XmlElement(ElementName="UnderlyingPriceFeedType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingPriceFeedType { get; set; }
		[XmlElement(ElementName="UnderlyingPriceSourcePage", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingPriceSourcePage { get; set; }
		[XmlElement(ElementName="SettlementISIN", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? SettlementISIN { get; set; }
		[XmlElement(ElementName="CorporateActionType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CorporateActionType { get; set; }
		[XmlElement(ElementName="UnderlyingText", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingText { get; set; }
		[XmlElement(ElementName="DeltaAtIssue", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DeltaAtIssue { get; set; }
		[XmlElement(ElementName="EffectiveFromDateDeltaAtIssue", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? EffectiveFromDateDeltaAtIssue { get; set; }
		[XmlElement(ElementName="NrOfSharesInInitialHedge", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? NrOfSharesInInitialHedge { get; set; }
		[XmlElement(ElementName="EffectiveFromDateSharesInHedge", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? EffectiveFromDateSharesInHedge { get; set; }
		[XmlElement(ElementName="IndexSponsor", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IndexSponsor { get; set; }
		[XmlElement(ElementName="UBSNonDeliverableFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UBSNonDeliverableFlag { get; set; }
		[XmlElement(ElementName="BreakEven", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BreakEven { get; set; }
		[XmlElement(ElementName="Delta", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? Delta { get; set; }
		[XmlElement(ElementName="DeltaPercentage", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DeltaPercentage { get; set; }
		[XmlElement(ElementName="LeverageFactor", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LeverageFactor { get; set; }
		[XmlElement(ElementName="Volatility", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? Volatility { get; set; }
		[XmlElement(ElementName="InstrumentIds", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public InstrumentIds? InstrumentIds { get; set; }
	}

	[XmlRoot(ElementName="Underlyings", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Underlyings {
		[XmlElement(ElementName="Underlying", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public List<Underlying>? Underlying { get; set; }
	}

	[XmlRoot(ElementName="CashDefinition", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class CashDefinition {
		[XmlElement(ElementName="PaymentRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentRate { get; set; }
		[XmlElement(ElementName="PaymentAmount", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentAmount { get; set; }
		[XmlElement(ElementName="PaymentCurrencyCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentCurrencyCode { get; set; }
		[XmlElement(ElementName="PaymentPremiumRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public List<string>? PaymentPremiumRate { get; set; }
		[XmlElement(ElementName="PaymentRateProRata", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentRateProRata { get; set; }
		[XmlElement(ElementName="PaymentInterestRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentInterestRate { get; set; }
		[XmlElement(ElementName="PaymentInterestRateProRata", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentInterestRateProRata { get; set; }
		[XmlElement(ElementName="PaymentPremiumRateProRata", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentPremiumRateProRata { get; set; }
		[XmlElement(ElementName="PaymentInterestAmount", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentInterestAmount { get; set; }
		[XmlElement(ElementName="PaymentWithholdingTaxBaseAmount", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentWithholdingTaxBaseAmount { get; set; }
	}

	[XmlRoot(ElementName="StrikeDetail", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class StrikeDetail {
		[XmlElement(ElementName="UnderlyingKey", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingKey { get; set; }
		[XmlElement(ElementName="StrikeLevel", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeLevel { get; set; }
		[XmlElement(ElementName="StrikeCurrencyCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeCurrencyCode { get; set; }
		[XmlElement(ElementName="StrikeFixingDateType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeFixingDateType { get; set; }
		[XmlElement(ElementName="StrikeFixingDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeFixingDate { get; set; }
		[XmlElement(ElementName="StrikeFixingDayPriceType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeFixingDayPriceType { get; set; }
		[XmlElement(ElementName="StrikeFixingTime", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeFixingTime { get; set; }
		[XmlElement(ElementName="StrikeFixingFunctionType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeFixingFunctionType { get; set; }
		[XmlElement(ElementName="StrikeFixingEndDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeFixingEndDate { get; set; }
		[XmlElement(ElementName="StrikeFixingPeriodicType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeFixingPeriodicType { get; set; }
		[XmlElement(ElementName="StrikeFixingInterval", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeFixingInterval { get; set; }
		[XmlElement(ElementName="StrikeFixingIntervalType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeFixingIntervalType { get; set; }
	}

	[XmlRoot(ElementName="StrikeDetails", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class StrikeDetails {
		[XmlElement(ElementName="StrikeDetail", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public List<StrikeDetail>? StrikeDetail { get; set; }
	}

	[XmlRoot(ElementName="StrikeDefinition", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class StrikeDefinition {
		[XmlElement(ElementName="StrikeDefinitionKey", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeDefinitionKey { get; set; }
		[XmlElement(ElementName="StrikeType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeType { get; set; }
		[XmlElement(ElementName="StrikeComparatorType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeComparatorType { get; set; }
		[XmlElement(ElementName="StrikeRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeRate { get; set; }
		[XmlElement(ElementName="ContractAmount", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ContractAmount { get; set; }
		[XmlElement(ElementName="UnderlyingSelectionType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingSelectionType { get; set; }
		[XmlElement(ElementName="UnderlyingValuationType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingValuationType { get; set; }
		[XmlElement(ElementName="ExerciseDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ExerciseDate { get; set; }
		[XmlElement(ElementName="ExerciseEndDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ExerciseEndDate { get; set; }
		[XmlElement(ElementName="ExercisePeriodicType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ExercisePeriodicType { get; set; }
		[XmlElement(ElementName="ExerciseInterval", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ExerciseInterval { get; set; }
		[XmlElement(ElementName="ExerciseIntervalType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ExerciseIntervalType { get; set; }
		[XmlElement(ElementName="MonitorPriceType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? MonitorPriceType { get; set; }
		[XmlElement(ElementName="VariableStrikeFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? VariableStrikeFlag { get; set; }
		[XmlElement(ElementName="StrikeParticipationScale", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StrikeParticipationScale { get; set; }
		[XmlElement(ElementName="StrikeDetails", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public StrikeDetails? StrikeDetails { get; set; }
	}

	[XmlRoot(ElementName="StrikeDefinitions", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class StrikeDefinitions {
		[XmlElement(ElementName="StrikeDefinition", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public StrikeDefinition? StrikeDefinition { get; set; }
	}

	[XmlRoot(ElementName="BarrierDetail", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class BarrierDetail {
		[XmlElement(ElementName="UnderlyingKey", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingKey { get; set; }
		[XmlElement(ElementName="BarrierLevel", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierLevel { get; set; }
		[XmlElement(ElementName="BarrierUpperLevel", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierUpperLevel { get; set; }
		[XmlElement(ElementName="BarrierCurrencyCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierCurrencyCode { get; set; }
		[XmlElement(ElementName="BarrierFixingDateType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierFixingDateType { get; set; }
		[XmlElement(ElementName="BarrierFixingDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierFixingDate { get; set; }
		[XmlElement(ElementName="BarrierHitDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierHitDate { get; set; }
		[XmlElement(ElementName="BarrierHitTime", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierHitTime { get; set; }
		[XmlElement(ElementName="BarrierHitLevel", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierHitLevel { get; set; }
		[XmlElement(ElementName="BarrierFixingDayPriceType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierFixingDayPriceType { get; set; }
		[XmlElement(ElementName="BarrierFixingTime", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierFixingTime { get; set; }
		[XmlElement(ElementName="BarrierFixingFunctionType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierFixingFunctionType { get; set; }
		[XmlElement(ElementName="BarrierFixingEndDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierFixingEndDate { get; set; }
		[XmlElement(ElementName="BarrierFixingPeriodicType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierFixingPeriodicType { get; set; }
		[XmlElement(ElementName="BarrierFixingInterval", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierFixingInterval { get; set; }
		[XmlElement(ElementName="BarrierFixingIntervalType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierFixingIntervalType { get; set; }
	}

	[XmlRoot(ElementName="BarrierDetails", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class BarrierDetails {
		[XmlElement(ElementName="BarrierDetail", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public List<BarrierDetail>? BarrierDetail { get; set; }
	}

	[XmlRoot(ElementName="BarrierDefinition", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class BarrierDefinition {
		[XmlElement(ElementName="AffectedStrikeDefinitionKey", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? AffectedStrikeDefinitionKey { get; set; }
		[XmlElement(ElementName="BarrierType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierType { get; set; }
		[XmlElement(ElementName="ComparatorType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ComparatorType { get; set; }
		[XmlElement(ElementName="BarrierRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierRate { get; set; }
		[XmlElement(ElementName="BarrierUpperRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierUpperRate { get; set; }
		[XmlElement(ElementName="QuantifierType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? QuantifierType { get; set; }
		[XmlElement(ElementName="QuantifierCount", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? QuantifierCount { get; set; }
		[XmlElement(ElementName="BarrierHitOrExcessReservoir", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierHitOrExcessReservoir { get; set; }
		[XmlElement(ElementName="UnderlyingSelectionType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingSelectionType { get; set; }
		[XmlElement(ElementName="UnderlyingValuationType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingValuationType { get; set; }
		[XmlElement(ElementName="MonitorPriceType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? MonitorPriceType { get; set; }
		[XmlElement(ElementName="ObservationBeginDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ObservationBeginDate { get; set; }
		[XmlElement(ElementName="ObservationEndDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ObservationEndDate { get; set; }
		[XmlElement(ElementName="ObservationDaysType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ObservationDaysType { get; set; }
		[XmlElement(ElementName="VariableBarrierFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? VariableBarrierFlag { get; set; }
		[XmlElement(ElementName="BarrierEventValueDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierEventValueDate { get; set; }
		[XmlElement(ElementName="BarrierEventValueDays", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierEventValueDays { get; set; }
		[XmlElement(ElementName="BarrierEventValueDaysType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierEventValueDaysType { get; set; }
		[XmlElement(ElementName="PaymentRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentRate { get; set; }
		[XmlElement(ElementName="PaymentAmount", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentAmount { get; set; }
		[XmlElement(ElementName="PaymentCurrencyCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentCurrencyCode { get; set; }
		[XmlElement(ElementName="ResidualRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ResidualRate { get; set; }
		[XmlElement(ElementName="ResidualAmount", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ResidualAmount { get; set; }
		[XmlElement(ElementName="BarrierDetails", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public BarrierDetails? BarrierDetails { get; set; }
	}

	[XmlRoot(ElementName="BarrierDefinitions", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class BarrierDefinitions {
		[XmlElement(ElementName="BarrierDefinition", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public BarrierDefinition? BarrierDefinition { get; set; }
	}

	[XmlRoot(ElementName="Payment", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Payment {
		[XmlElement(ElementName="PaymentType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentType { get; set; }
		[XmlElement(ElementName="DependUnderlyingRoleType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DependUnderlyingRoleType { get; set; }
		[XmlElement(ElementName="PaymentValueDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentValueDate { get; set; }
		[XmlElement(ElementName="PaymentValueDays", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentValueDays { get; set; }
		[XmlElement(ElementName="PaymentValueDaysType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentValueDaysType { get; set; }
		[XmlElement(ElementName="SettlementType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? SettlementType { get; set; }
		[XmlElement(ElementName="FractionMgmtType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FractionMgmtType { get; set; }
		[XmlElement(ElementName="DetachmentType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DetachmentType { get; set; }
		[XmlElement(ElementName="PaymentCapLevel", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentCapLevel { get; set; }
		[XmlElement(ElementName="PaymentCapRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentCapRate { get; set; }
		[XmlElement(ElementName="PaymentFloorLevel", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentFloorLevel { get; set; }
		[XmlElement(ElementName="PaymentFloorRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentFloorRate { get; set; }
		[XmlElement(ElementName="PaymentFixingDateType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentFixingDateType { get; set; }
		[XmlElement(ElementName="PaymentFixingDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentFixingDate { get; set; }
		[XmlElement(ElementName="PaymentFixingDayPriceType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentFixingDayPriceType { get; set; }
		[XmlElement(ElementName="PaymentFixingTime", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentFixingTime { get; set; }
		[XmlElement(ElementName="PaymentFixingFunctionType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentFixingFunctionType { get; set; }
		[XmlElement(ElementName="PaymentFixingEndDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentFixingEndDate { get; set; }
		[XmlElement(ElementName="PaymentFixingPeriodicType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentFixingPeriodicType { get; set; }
		[XmlElement(ElementName="PaymentFixingInterval", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentFixingInterval { get; set; }
		[XmlElement(ElementName="PaymentFixingIntervalType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentFixingIntervalType { get; set; }
		[XmlElement(ElementName="PaymentCutoff", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentCutoff { get; set; }
		[XmlElement(ElementName="IncomeType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IncomeType { get; set; }
		[XmlElement(ElementName="EarningSpecificationType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? EarningSpecificationType { get; set; }
		[XmlElement(ElementName="EarningBeginDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? EarningBeginDate { get; set; }
		[XmlElement(ElementName="EarningEndDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? EarningEndDate { get; set; }
		[XmlElement(ElementName="EarningNumberOfDays", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? EarningNumberOfDays { get; set; }
		[XmlElement(ElementName="CurrentDenomination", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CurrentDenomination { get; set; }
		[XmlElement(ElementName="CurrencyPairFixingDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CurrencyPairFixingDate { get; set; }
		[XmlElement(ElementName="CurrencyPairFixingTime", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CurrencyPairFixingTime { get; set; }
		[XmlElement(ElementName="CashDefinition", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public CashDefinition? CashDefinition { get; set; }
		[XmlElement(ElementName="PaymentDescription", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentDescription { get; set; }
		[XmlElement(ElementName="StrikeDefinitions", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public StrikeDefinitions? StrikeDefinitions { get; set; }
		[XmlElement(ElementName="BarrierDefinitions", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public BarrierDefinitions? BarrierDefinitions { get; set; }
		[XmlElement(ElementName="PaymentTriggerFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentTriggerFlag { get; set; }
		[XmlElement(ElementName="PaymentExDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentExDate { get; set; }
		[XmlElement(ElementName="PaymentEligibilityDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentEligibilityDate { get; set; }
		[XmlElement(ElementName="FractionMgmtTyp", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FractionMgmtTyp { get; set; }
	}

	[XmlRoot(ElementName="Payments", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Payments {
		[XmlElement(ElementName="Payment", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public List<Payment>? Payment { get; set; }
	}

	[XmlRoot(ElementName="TradingVenue", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class TradingVenue {
		[XmlElement(ElementName="TradingExchangeCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? TradingExchangeCode { get; set; }
		[XmlElement(ElementName="TradingCurrencyCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? TradingCurrencyCode { get; set; }
		[XmlElement(ElementName="ContributorPriceSourcePage", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ContributorPriceSourcePage { get; set; }
		[XmlElement(ElementName="FirstTradingDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FirstTradingDate { get; set; }
		[XmlElement(ElementName="LastTradingDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LastTradingDate { get; set; }
		[XmlElement(ElementName="LastTradingTime", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LastTradingTime { get; set; }
		[XmlElement(ElementName="TradingSymbol", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? TradingSymbol { get; set; }
		[XmlElement(ElementName="SmallestTradeableUnit", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? SmallestTradeableUnit { get; set; }
		[XmlElement(ElementName="DirtyFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DirtyFlag { get; set; }
	}

	[XmlRoot(ElementName="TradingVenues", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class TradingVenues {
		[XmlElement(ElementName="TradingVenue", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public TradingVenue? TradingVenue { get; set; }
	}

	[XmlRoot(ElementName="Ratings", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Ratings {
		[XmlElement(ElementName="Moodys", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? Moodys { get; set; }
		[XmlElement(ElementName="StandardAndPoors", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? StandardAndPoors { get; set; }
		[XmlElement(ElementName="Fitch", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? Fitch { get; set; }
	}

	[XmlRoot(ElementName="Party", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Party {
		[XmlElement(ElementName="PartyType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PartyType { get; set; }
		[XmlElement(ElementName="TKPartyKey", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? TKPartyKey { get; set; }
		[XmlElement(ElementName="SISPartyBPId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? SISPartyBPId { get; set; }
		[XmlElement(ElementName="BBCompanyId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BBCompanyId { get; set; }
		[XmlElement(ElementName="WMPartyId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? WMPartyId { get; set; }
		[XmlElement(ElementName="XetraPartyId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? XetraPartyId { get; set; }
		[XmlElement(ElementName="LEI", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LEI { get; set; }
		[XmlElement(ElementName="KVPartyId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? KVPartyId { get; set; }
		[XmlElement(ElementName="OeKBId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? OeKBId { get; set; }
		[XmlElement(ElementName="BIC", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BIC { get; set; }
		[XmlElement(ElementName="PartyName", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PartyName { get; set; }
		[XmlElement(ElementName="PartyAreaCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PartyAreaCode { get; set; }
		[XmlElement(ElementName="PartyLocation", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PartyLocation { get; set; }
		[XmlElement(ElementName="CustodyType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CustodyType { get; set; }
		[XmlElement(ElementName="CertificationType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CertificationType { get; set; }
		[XmlElement(ElementName="GuaranteeType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? GuaranteeType { get; set; }
		[XmlElement(ElementName="Rating", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? Rating { get; set; }
		[XmlElement(ElementName="Ratings", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public Ratings? Ratings { get; set; }
	}

	[XmlRoot(ElementName="Parties", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Parties {
		[XmlElement(ElementName="Party", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public List<Party>? Party { get; set; }
	}

	[XmlRoot(ElementName="DistributionRestriction", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class DistributionRestriction {
		[XmlElement(ElementName="DistributionAreaCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DistributionAreaCode { get; set; }
		[XmlElement(ElementName="DistributionAudienceType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DistributionAudienceType { get; set; }
		[XmlElement(ElementName="PublicOfferingStartDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PublicOfferingStartDate { get; set; }
		[XmlElement(ElementName="PublicOfferingEndDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PublicOfferingEndDate { get; set; }
		[XmlElement(ElementName="DerinetDisplayLevel", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DerinetDisplayLevel { get; set; }
	}

	[XmlRoot(ElementName="DistributionRestrictions", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class DistributionRestrictions {
		[XmlElement(ElementName="DistributionRestriction", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public List<DistributionRestriction>? DistributionRestriction { get; set; }
	}

	[XmlRoot(ElementName="TransactionRestriction", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class TransactionRestriction {
		[XmlElement(ElementName="TransactionType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? TransactionType { get; set; }
		[XmlElement(ElementName="TransactionAreaCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? TransactionAreaCode { get; set; }
		[XmlElement(ElementName="RestrictionAreaCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RestrictionAreaCode { get; set; }
		[XmlElement(ElementName="ExcludedRestrictionAreaCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ExcludedRestrictionAreaCode { get; set; }
		[XmlElement(ElementName="RestrictionSubjectType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RestrictionSubjectType { get; set; }
		[XmlElement(ElementName="RestrictionDays", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RestrictionDays { get; set; }
		[XmlElement(ElementName="RestrictionBeginDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RestrictionBeginDate { get; set; }
		[XmlElement(ElementName="RestrictionEndDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RestrictionEndDate { get; set; }
		[XmlElement(ElementName="RestrictionMaxAmount", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RestrictionMaxAmount { get; set; }
		[XmlElement(ElementName="RestrictionMinAmount", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RestrictionMinAmount { get; set; }
		[XmlElement(ElementName="RestrictionCurrencyCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RestrictionCurrencyCode { get; set; }
		[XmlElement(ElementName="RestrictionDescription", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RestrictionDescription { get; set; }
	}

	[XmlRoot(ElementName="TransactionRestrictions", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class TransactionRestrictions {
		[XmlElement(ElementName="TransactionRestriction", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public List<TransactionRestriction>? TransactionRestriction { get; set; }
	}

	[XmlRoot(ElementName="Instrument", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class Instrument {
		[XmlElement(ElementName="ProductDescriptionURL", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ProductDescriptionURL { get; set; }
		[XmlElement(ElementName="ProductNameFull", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ProductNameFull { get; set; }
		[XmlElement(ElementName="FISN", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FISN { get; set; }
		[XmlElement(ElementName="ProductBrand", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ProductBrand { get; set; }
		[XmlElement(ElementName="IBTTypeCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IBTTypeCode { get; set; }
		[XmlElement(ElementName="CollateralisationType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? CollateralisationType { get; set; }
		[XmlElement(ElementName="PrivatePlacementFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PrivatePlacementFlag { get; set; }
		[XmlElement(ElementName="ListedFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ListedFlag { get; set; }
		[XmlElement(ElementName="IssueCurrencyCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IssueCurrencyCode { get; set; }
		[XmlElement(ElementName="Denomination", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? Denomination { get; set; }
		[XmlElement(ElementName="DayCountMethodType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DayCountMethodType { get; set; }
		[XmlElement(ElementName="IssuePrice", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IssuePrice { get; set; }
		[XmlElement(ElementName="IssuePriceRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IssuePriceRate { get; set; }
		[XmlElement(ElementName="InstrumentQuotationType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InstrumentQuotationType { get; set; }
		[XmlElement(ElementName="BasketCoverRatio", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BasketCoverRatio { get; set; }
		[XmlElement(ElementName="BasketInitialPrice", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BasketInitialPrice { get; set; }
		[XmlElement(ElementName="DiscountRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? DiscountRate { get; set; }
		[XmlElement(ElementName="IssueCapitalisation", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IssueCapitalisation { get; set; }
		[XmlElement(ElementName="MaxYieldRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? MaxYieldRate { get; set; }
		[XmlElement(ElementName="IssueIncreaseFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IssueIncreaseFlag { get; set; }
		[XmlElement(ElementName="NumberInIssue", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? NumberInIssue { get; set; }
		[XmlElement(ElementName="RedemptionDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? RedemptionDate { get; set; }
		[XmlElement(ElementName="OrdinaryTerminationDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? OrdinaryTerminationDate { get; set; }
		[XmlElement(ElementName="OpenEndFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? OpenEndFlag { get; set; }
		[XmlElement(ElementName="BarrierHitFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BarrierHitFlag { get; set; }
		[XmlElement(ElementName="OrderServiceFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? OrderServiceFlag { get; set; }
		[XmlElement(ElementName="InvestorPutabilityFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InvestorPutabilityFlag { get; set; }
		[XmlElement(ElementName="IssuerCallabilityFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IssuerCallabilityFlag { get; set; }
		[XmlElement(ElementName="IssuerProlongationFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IssuerProlongationFlag { get; set; }
		[XmlElement(ElementName="AmortisableFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? AmortisableFlag { get; set; }
		[XmlElement(ElementName="LeverageProductFlag", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LeverageProductFlag { get; set; }
		[XmlElement(ElementName="InvestorConversionType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InvestorConversionType { get; set; }
		[XmlElement(ElementName="MainUnderlyingAssetType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? MainUnderlyingAssetType { get; set; }
		[XmlElement(ElementName="UnderlyingMgmtType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? UnderlyingMgmtType { get; set; }
		[XmlElement(ElementName="IssueDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IssueDate { get; set; }
		[XmlElement(ElementName="IssueTime", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? IssueTime { get; set; }
		[XmlElement(ElementName="PaymentDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PaymentDate { get; set; }
		[XmlElement(ElementName="SubscriptionBeginDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? SubscriptionBeginDate { get; set; }
		[XmlElement(ElementName="SubscriptionEndDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? SubscriptionEndDate { get; set; }
		[XmlElement(ElementName="SubscriptionEndTime", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? SubscriptionEndTime { get; set; }
		[XmlElement(ElementName="InitialFixingDateType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InitialFixingDateType { get; set; }
		[XmlElement(ElementName="InitialFixingDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InitialFixingDate { get; set; }
		[XmlElement(ElementName="InitialFixingDayPriceType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InitialFixingDayPriceType { get; set; }
		[XmlElement(ElementName="InitialFixingTime", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InitialFixingTime { get; set; }
		[XmlElement(ElementName="InitialFixingFunctionType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InitialFixingFunctionType { get; set; }
		[XmlElement(ElementName="InitialFixingEndDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InitialFixingEndDate { get; set; }
		[XmlElement(ElementName="InitialFixingPeriodicType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InitialFixingPeriodicType { get; set; }
		[XmlElement(ElementName="InitialFixingInterval", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InitialFixingInterval { get; set; }
		[XmlElement(ElementName="InitialFixingIntervalType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? InitialFixingIntervalType { get; set; }
		[XmlElement(ElementName="BusinessDayConventionType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BusinessDayConventionType { get; set; }
		[XmlElement(ElementName="BondYieldRate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BondYieldRate { get; set; }
		[XmlElement(ElementName="LegalSecurityType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LegalSecurityType { get; set; }
		[XmlElement(ElementName="SecurityRankingType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? SecurityRankingType { get; set; }
		[XmlElement(ElementName="ConversionGuaranteeType", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? ConversionGuaranteeType { get; set; }
		[XmlElement(ElementName="JurisdictionAreaCode", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? JurisdictionAreaCode { get; set; }
		[XmlElement(ElementName="LegalVenue", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? LegalVenue { get; set; }
		[XmlElement(ElementName="FinalTermsId", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? FinalTermsId { get; set; }
		[XmlElement(ElementName="BaseProspectusCreationDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BaseProspectusCreationDate { get; set; }
		[XmlElement(ElementName="BaseProspectusPublicationDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? BaseProspectusPublicationDate { get; set; }
		[XmlElement(ElementName="PublicOfferingDate", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public string? PublicOfferingDate { get; set; }
		[XmlElement(ElementName="InstrumentClassifications", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public InstrumentClassifications? InstrumentClassifications { get; set; }
		[XmlElement(ElementName="IncomeData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public IncomeData? IncomeData { get; set; }
		[XmlElement(ElementName="CHTaxData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public CHTaxData? CHTaxData { get; set; }
		[XmlElement(ElementName="EUTaxData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public EUTaxData? EUTaxData { get; set; }
		[XmlElement(ElementName="USTaxData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public USTaxData? USTaxData { get; set; }
		[XmlElement(ElementName="UKTaxData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public UKTaxData? UKTaxData { get; set; }
		[XmlElement(ElementName="ATTaxData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public ATTaxData? ATTaxData { get; set; }
		[XmlElement(ElementName="ITTaxData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public ITTaxData? ITTaxData { get; set; }
		[XmlElement(ElementName="Fees", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public Fees? Fees { get; set; }
		[XmlElement(ElementName="InstrumentIds", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public InstrumentIds? InstrumentIds { get; set; }
		[XmlElement(ElementName="Underlyings", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public Underlyings? Underlyings { get; set; }
		[XmlElement(ElementName="Payments", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public Payments? Payments { get; set; }
		[XmlElement(ElementName="TradingVenues", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public TradingVenues? TradingVenues { get; set; }
		[XmlElement(ElementName="Parties", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public Parties? Parties { get; set; }
		[XmlElement(ElementName="DistributionRestrictions", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public DistributionRestrictions? DistributionRestrictions { get; set; }
		[XmlElement(ElementName="TransactionRestrictions", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public TransactionRestrictions? TransactionRestrictions { get; set; }
	}

	[XmlRoot(ElementName="IBTTermSheet", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
	public class IBTTermSheet {
		[XmlElement(ElementName="AdminData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public AdminData? AdminData { get; set; }
		[XmlElement(ElementName="Events", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public Events? Events { get; set; }
		[XmlElement(ElementName="Contacts", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public Contacts? Contacts { get; set; }
		[XmlElement(ElementName="RegulatoryData", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public RegulatoryData? RegulatoryData { get; set; }
		[XmlElement(ElementName="Instrument", Namespace="http://schemas.vontobel.com/dataservice/v1.0")]
		public Instrument? Instrument { get; set; }
		[XmlAttribute(AttributeName="xmlns")]
		public string? Xmlns { get; set; }
	}

}
